export function getNameMeaning(dinosaur) {

  switch(dinosaur) {

  case 'Aardonyx': return 'Earth claw';
  case 'Abelisaurus': return 'Abel\'s lizard';
  case 'Achelousaurus': return 'Achelous\' lizard';
  case 'Achillobator': return 'Achilles hero';
  case 'Acrocanthosaurus': return 'high-spined lizard';
  case 'Aegyptosaurus': return 'Egyptian lizard';
  case 'Afrovenator': return 'African hunter';
  case 'Agilisaurus': return 'agile lizard';
  case 'Alamosaurus': return 'Alamo lizard';
  case 'Albertaceratops': return 'Alberta horned face';
  case 'Albertosaurus': return 'Alberta lizard';
  case 'Alectrosaurus': return 'eagle lizard';
  case 'Alioramus': return 'other [evolutionary] branch';
  case 'Allosaurus': return 'other lizard';
  case 'Alvarezsaurus': return 'Alvarez\'s lizard';
  case 'Amargasaurus': return 'Amarga lizard';
  case 'Ammosaurus': return 'sand lizard';
  case 'Ampelosaurus': return 'vineyard lizard';
  case 'Amygdalodon': return 'almond tooth';
  case 'Anchiceratops': return 'near horned lizard';
  case 'Anchisaurus': return 'near lizard';
  case 'Ankylosaurus': return 'stiff lizard';
  case 'Anserimimus': return 'goose mimic';
  case 'Antarctosaurus': return 'non-northern lizard';
  case 'Apatosaurus': return 'deceptive lizard';
  case 'Aragosaurus': return 'AragÃ³n lizard';
  case 'Aralosaurus': return 'Aral lizard';
  case 'Archaeoceratops': return 'ancient horned face';
  case 'Archaeopteryx': return 'ancient wing';
  case 'Archaeornithomimus': return 'ancient bird mimic';
  case 'Argentinosaurus': return 'Argentina lizard';
  case 'Arrhinoceratops': return 'without-nose-horn face';
  case 'Atlascopcosaurus': return 'Atlas Copco lizard';
  case 'Aucasaurus': return 'Auca lizard';
  case 'Austrosaurus': return 'south lizard';
  case 'Avaceratops': return 'Ava\'s horned face';
  case 'Avimimus': return 'bird mimic';
  case 'Bactrosaurus': return 'club [spined] lizard';
  case 'Bagaceratops': return 'small-horned face';
  case 'Bambiraptor': return 'Bambi plunderer';
  case 'Barapasaurus': return 'big leg lizard';
  case 'Barosaurus': return 'heavy lizard';
  case 'Baryonyx': return 'heavy claw';
  case 'Becklespinax': return 'Beckles\' spinax';
  case 'Beipiaosaurus': return 'Beipiao lizard';
  case 'Bellusaurus': return 'fine lizard';
  case 'Borogovia': return 'borogove';
  case 'Brachiosaurus': return 'arm lizard';
  case 'Brachylophosaurus': return 'short-crested lizard';
  case 'Brachytrachelopan': return 'short-necked Pan [shepherd god]';
  case 'Buitreraptor': return 'Buitrera (vulture roost) plunderer';
  case 'Camarasaurus': return 'chambered lizard';
  case 'Camptosaurus': return 'bent lizard';
  case 'Carcharodontosaurus': return 'Carcharodon lizard';
  case 'Carnotaurus': return 'carnivorous bull';
  case 'Caudipteryx': return 'tail feather';
  case 'Cedarpelta': return 'Cedar [Mountain Formation] shield';
  case 'Centrosaurus': return 'sharp pointed lizard';
  case 'Ceratosaurus': return 'horned lizard';
  case 'Cetiosauriscus': return 'like whale lizard';
  case 'Cetiosaurus': return 'whale lizard';
  case 'Chaoyangsaurus': return 'Chaoyang lizard';
  case 'Chasmosaurus': return 'chasm lizard';
  case 'Chindesaurus': return 'Chinde lizard';
  case 'Chinshakiangosaurus': return 'Chinshakiang lizard';
  case 'Chirostenotes': return 'narrow-handed';
  case 'Chubutisaurus': return 'Chubut [Province] lizard';
  case 'Chungkingosaurus': return 'Chongqing lizard';
  case 'Citipati': return 'lord of the funeral pyre';
  case 'Coelophysis': return 'hollow form';
  case 'Coelurus': return 'hollow tail';
  case 'Coloradisaurus': return '[Los] Colorados lizard';
  case 'Compsognathus': return 'pretty jaw';
  case 'Conchoraptor': return 'conch thief';
  case 'Confuciusornis': return 'Confucius bird';
  case 'Corythosaurus': return 'Corinthian helmet lizard';
  case 'Cryolophosaurus': return 'frozen crested lizard';
  case 'Dacentrurus': return 'pointed tail';
  case 'Daspletosaurus': return 'frightful lizard';
  case 'Datousaurus': return 'Datou lizard';
  case 'Deinocheirus': return 'terrible hand';
  case 'Deltadromeus': return 'delta runner';
  case 'Dicraeosaurus': return 'forked lizard';
  case 'Dilophosaurus': return 'two-ridged lizard';
  case 'Diplodocus': return 'double beam';
  case 'Dromaeosaurus': return 'running lizard';
  case 'Dromiceiomimus': return 'emu mimic';
  case 'Dryosaurus': return 'oak lizard';
  case 'Dryptosaurus': return 'tearing lizard';
  case 'Edmontonia': return 'of Edmonton';
  case 'Edmontosaurus': return 'Edmonton lizard';
  case 'Einiosaurus': return 'bison lizard';
  case 'Elaphrosaurus': return 'fleet lizard';
  case 'Emausaurus': return 'EMAU (Ernst-Moritz-Arndt-Universität) lizard';
  case 'Eoraptor': return 'early plunderer';
  case 'Eotyrannus': return 'dawn tyrant';
  case 'Erketu': return 'Erketu = Tengri (a Mongolian creator-god)';
  case 'Erlikosaurus': return 'Erlik''s lizard';
  case 'Euhelopus': return '1 marsh foot';
  case 'Euoplocephalus': return 'well-armoured head';
  case 'Europasaurus': return 'Europe lizard';
  case 'Eustreptospondylus': return 'well-curved vertebra';
  case 'Fukuiraptor': return 'Fukui plunderer';
  case 'Gallimimus': return 'chicken mimic';
  case 'Gargoyleosaurus': return 'gargoyle lizard';
  case 'Garudimimus': return 'Garuda mimic';
  case 'Gasosaurus': return 'gas lizard';
  case 'Gasparinisaura': return 'Gasparini\'s lizard';
  case 'Gastonia': return '[Robert] Gaston';
  case 'Giganotosaurus': return 'giant southern lizard';
  case 'Gilmoreosaurus': return 'Gilmore\'s lizard';
  case 'Giraffatitan': return 'giraffe titan';
  case 'Gobisaurus': return 'Gobi lizard';
  case 'Gorgosaurus': return 'fierce lizard';
  case 'Goyocephale': return 'decorated head';
  case 'Gryposaurus': return 'hook-nosed lizard';
  case 'Guaibasaurus': return '[Rio] Guaiba lizard';
  case 'Guanlong': return 'crowned dragon';
  case 'Hadrosaurus': return 'big lizard';
  case 'Hagryphus': return 'Ha (Egyptian god of the western desert) griffin';
  case 'Haplocanthosaurus': return 'simple-spined lizard';
  case 'Harpymimus': return 'harpy mimic';
  case 'Herrerasaurus': return 'Herrera\'s lizard';
  case 'Hesperosaurus': return 'western lizard';
  case 'Heterodontosaurus': return 'different-teeth lizard';
  case 'Heyuannia': return 'from [the city of] Heyuan';
  case 'Homalocephale': return 'level head';
  case 'Huayangosaurus': return 'Huayang lizard';
  case 'Hylaeosaurus': return 'woodland lizard';
  case 'Hypacrosaurus': return 'near-topmost lizard';
  case 'Hypsilophodon': return 'high-ridge tooth';
  case 'Iguanodon': return 'iguana tooth';
  case 'Indosuchus': return 'Indian crocodile';
  case 'Irritator': return 'irritator';
  case 'Janenschia': return 'named after Janansch';
  case 'Jaxartosaurus': return 'Jaxartes [River] lizard';
  case 'Jingshanosaurus': return 'Jingshan lizard';
  case 'Jobaria': return 'Jobar (mythical animal)';
  case 'Juravenator': return 'Jura (Bavarian mountains) hunter';
  case 'Kentrosaurus': return 'spiky lizard';
  case 'Khaan': return 'ruler';
  case 'Kotasaurus': return 'Kota lizard';
  case 'Kritosaurus': return 'noble lizard';
  case 'Lambeosaurus': return 'Lambe\'s lizard';
  case 'Leaellynasaura': return 'Leaellyn\'s lizard';
  case 'Leptoceratops': return 'slim horned face';
  case 'Ligabuesaurus': return '[Dr Giancarlo] Ligabue lizard';
  case 'Liliensternus': return '[for] Lilienstern';
  case 'Lophorhothon': return 'crested nose';
  case 'Lophostropheus': return 'crested verebra';
  case 'Lufengosaurus': return 'Lufeng lizard';
  case 'Lurdusaurus': return 'heavy lizard';
  case 'Lycorhinus': return 'wolf snout';
  case 'Magyarosaurus': return 'Magyar lizard';
  case 'Maiasaura': return 'good mother lizard';
  case 'Majungasaurus': return 'Majunga lizard';
  case 'Malawisaurus': return 'Malawi lizard';
  case 'Mamenchisaurus': return 'Mamenchi lizard';
  case 'Mapusaurus': return 'Earth (Mapuche language, Patagonia) lizard';
  case 'Marshosaurus': return '[Othniel Charles] Marsh lizard';
  case 'Masiakasaurus': return 'vicious lizard';
  case 'Massospondylus': return 'massive vertebrae';
  case 'Maxakalisaurus': return 'Maxakali (tribe of Brazil) lizard';
  case 'Megalosaurus': return 'big lizard';
  case 'Melanorosaurus': return 'Black [Mountain] lizard';
  case 'Metriacanthosaurus': return 'moderately-spined lizard';
  case 'Microceratus': return 'tiny horned';
  case 'Micropachycephalosaurus': return 'tiny thick-headed lizard';
  case 'Microraptor': return 'tiny plunderer';
  case 'Minmi': return 'named after Minmi Crossing, Queensland';
  case 'Monolophosaurus': return 'single-crested lizard';
  case 'Mononykus': return 'single claw';
  case 'Mussaurus': return 'mouse lizard';
  case 'Muttaburrasaurus': return 'Muttaburra lizard';
  case 'Nanshiungosaurus': return 'Nanxiong lizard';
  case 'Nedoceratops': return 'insufficient horned face';
  case 'Nemegtosaurus': return 'Nemegt lizard';
  case 'Neovenator': return 'new hunter';
  case 'Neuquenosaurus': return 'NeuquÃ©n lizard';
  case 'Nigersaurus': return 'Niger lizard';
  case 'Noasaurus': return 'northwestern Argentina lizard';
  case 'Nodosaurus': return 'node lizard';
  case 'Nomingia': return 'Nomingiin';
  case 'Nothronychus': return 'sloth-like claw';
  case 'Nqwebasaurus': return 'Nqweba lizard';
  case 'Omeisaurus': return 'Omei lizard';
  case 'Opisthocoelicaudia': return 'hollow-backed tail [vertebrae]';
  case 'Ornitholestes': return 'bird robber';
  case 'Ornithomimus': return 'bird mimic';
  case 'Orodromeus': return 'mountain runner';
  case 'Oryctodromeus': return 'digging runner';
  case 'Othnielia': return '[for] Othniel [Marsh]';
  case 'Ouranosaurus': return 'brave monitor lizard';
  case 'Oviraptor': return 'egg thief';
  case 'Pachycephalosaurus': return 'thick-headed lizard';
  case 'Pachyrhinosaurus': return 'thick-nosed lizard';
  case 'Panoplosaurus': return 'fully-armoured lizard';
  case 'Pantydraco': return 'Pant-y-ffynnon dragon';
  case 'Paralititan': return 'tidal giant';
  case 'Parasaurolophus': return 'like Saurolophus';
  case 'Parksosaurus': return 'Park\'s lizard';
  case 'Patagosaurus': return 'Patagonian lizard';
  case 'Pelicanimimus': return 'pelican mimic';
  case 'Pentaceratops': return 'five-horned face';
  case 'Saichania': return 'beautiful';
  case 'Saltasaurus': return 'Salta lizard';
  case 'Sarcosaurus': return 'flesh lizard';
  case 'Saurolophus': return 'ridged lizard';
  case 'Sauropelta': return 'lizard shield';
  case 'Saurophaganax': return 'king of the lizard eaters';
  case 'Saurornithoides': return 'bird-like lizard';
  case 'Scelidosaurus': return 'limb lizard';
  case 'Scutellosaurus': return 'small shield lizard';
  case 'Secernosaurus': return 'separated lizard';
  case 'Segisaurus': return 'Segi [Canyon] lizard';
  case 'Segnosaurus': return 'slow lizard';
  case 'Shanag': return 'named after the dancers in the Buddhist Tsam festival';
  case 'Shantungosaurus': return 'Shantung (=Shandong) lizard';
  case 'Shunosaurus': return 'Shuno lizard';
  case 'Shuvuuia': return 'bird';
  case 'Silvisaurus': return 'forest lizard';
  case 'Sinocalliopteryx': return 'Chinese beautiful feather';
  case 'Sinornithosaurus': return 'Chinese bird lizard';
  case 'Sinosauropteryx': return 'Chinese lizard wing';
  case 'Sinovenator': return 'Chinese hunter';
  case 'Sinraptor': return 'Chinese plunderer';
  case 'Sonidosaurus': return 'Sonid (area in which the type locality is) lizard';
  case 'Spinosaurus': return 'thorn lizard';
  case 'Staurikosaurus': return 'Southern Cross lizard';
  case 'Stegoceras': return 'horny roof';
  case 'Stegosaurus': return 'roof lizard';
  case 'Stenopelix': return 'narrow pelvis';
  case 'Struthiomimus': return 'ostrich mimic';
  case 'Struthiosaurus': return 'ostrich lizard';
  case 'Styracosaurus': return 'spiked lizard';
  case 'Suchomimus': return 'crocodile mimic';
  case 'Supersaurus': return 'super lizard';
  case 'Talarurus': return 'wicker tail';
  case 'Tarbosaurus': return 'alarming lizard';
  case 'Tarchia': return 'brainy one';
  case 'Telmatosaurus': return 'swamp lizard';
  case 'Tenontosaurus': return 'sinew lizard';
  case 'Thecodontosaurus': return 'socket-toothed lizard';
  case 'Thescelosaurus': return 'wonderful lizard';
  case 'Torosaurus': return 'bull lizard';
  case 'Torvosaurus': return 'savage lizard';
  case 'Triceratops': return 'three-horned face';
  case 'Troodon': return 'wounding tooth';
  case 'Tsintaosaurus': return 'Qingdao lizard';
  case 'Tuojiangosaurus': return 'Tuo River lizard';
  case 'Tylocephale': return 'swelling head';
  case 'Tyrannosaurus': return 'tyrant lizard';
  case 'Unenlagia': return 'half bird';
  case 'Urbacodon': return 'URBAC tooth';
  case 'Utahraptor': return 'Utah plunderer';
  case 'Valdosaurus': return 'Wealden lizard';
  case 'Velociraptor': return 'quick plunderer';
  case 'Vulcanodon': return 'volcano tooth';
  case 'Yandusaurus': return 'Yandu lizard';
  case 'Yangchuanosaurus': return 'Yangchuan lizard';
  case 'Yimenosaurus': return 'Yimen lizard';
  case 'Yinlong': return 'hidden dragon';
  case 'Yuanmousaurus': return 'Yuanmou (area where the type locality is) lizard';
  case 'Yunnanosaurus': return 'Yunnan lizard';
  case 'Zalmoxes': return 'Zalmoxes (Dacian deity)';
  case 'Zephyrosaurus': return 'west wind lizard';

}
}
