from random import choice
import json
import requests
from bs4 import BeautifulSoup
import threading
from functools import wraps


def delay(delay=0.):
    def wrap(f):
        @wraps(f)
        def delayed(*args, **kwargs):
            timer = threading.Timer(delay, f, args=args, kwargs=kwargs)
            timer.start()
        return delayed
    return wrap


class Timer():
    toClearTimer = False
    def setTimeout(self, fn, time):
        isInvokationCancelled = False
        @delay(time)
        def some_fn():
                if (self.toClearTimer is False):
                        fn()
                else:
                    print('Invocation cleared.')
        some_fn()
        return isInvokationCancelled
    def setClearTimer(self):
        self.toClearTimer = True

_user_agents = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'
]


class NaturalHistoryMuseumScraper:

    def __init__(self, user_agents=_user_agents, proxy=None):
        self.user_agents = user_agents
        self.proxy = proxy

    def scrape_dinosaur_name_meanings(self, dinosaur_name):
        url = 'http://www.nhm.ac.uk/discover/dino-directory/' + dinosaur_name + '.html'
        r = requests.get(url)
        soup = BeautifulSoup(r.content, features="html.parser")
        meaning = soup.find('dd', class_="dinosaur--meaning")
        if meaning is not None:
            print("NOT NONE")
        else:
            return ""

        return meaning.text

    def print_meaning(self, dinosaur):
        print(dinosaur + self.scrape_dinosaur_name_meanings(dinosaur))

    def meanings(self):
        dinosaur_names = [
           "Aardonyx",
           "Abelisaurus",
           "Achelousaurus",
           "Achillobator",
           "Acrocanthosaurus",
           "Aegyptosaurus",
           "Afrovenator",
           "Agilisaurus",
           "Alamosaurus",
           "Albertaceratops",
           "Albertosaurus",
           "Alectrosaurus",
           "Alioramus",
           "Allosaurus",
           "Alvarezsaurus",
           "Amargasaurus",
           "Ammosaurus",
           "Ampelosaurus",
           "Amygdalodon",
           "Anchiceratops",
           "Anchisaurus",
           "Ankylosaurus",
           "Anserimimus",
           "Antarctosaurus",
           "Apatosaurus",
           "Aragosaurus",
           "Aralosaurus",
           "Archaeoceratops",
           "Archaeopteryx",
           "Archaeornithomimus",
           "Argentinosaurus",
           "Arrhinoceratops",
           "Atlascopcosaurus",
           "Aucasaurus",
           "Austrosaurus",
           "Avaceratops",
           "Avimimus",
           "Bactrosaurus",
           "Bagaceratops",
           "Bambiraptor",
           "Barapasaurus",
           "Barosaurus",
           "Baryonyx",
           "Becklespinax",
           "Beipiaosaurus",
           "Bellusaurus",
           "Borogovia",
           "Brachiosaurus",
           "Brachylophosaurus",
           "Brachytrachelopan",
           "Buitreraptor",
           "Camarasaurus",
           "Camptosaurus",
           "Carcharodontosaurus",
           "Carnotaurus",
           "Caudipteryx",
           "Cedarpelta",
           "Centrosaurus",
           "Ceratosaurus",
           "Cetiosauriscus",
           "Cetiosaurus",
           "Chaoyangsaurus",
           "Chasmosaurus",
           "Chindesaurus",
           "Chinshakiangosaurus",
           "Chirostenotes",
           "Chubutisaurus",
           "Chungkingosaurus",
           "Citipati",
           "Coelophysis",
           "Coelurus",
           "Coloradisaurus",
           "Compsognathus",
           "Conchoraptor",
           "Confuciusornis",
           "Corythosaurus",
           "Cryolophosaurus",
           "Dacentrurus",
           "Daspletosaurus",
           "Datousaurus",
           "Deinocheirus",
           "Deltadromeus",
           "Dicraeosaurus",
           "Dilophosaurus",
           "Diplodocus",
           "Dromaeosaurus",
           "Dromiceiomimus",
           "Dryosaurus",
           "Dryptosaurus",
           "Edmontonia",
           "Edmontosaurus",
           "Einiosaurus",
           "Elaphrosaurus",
           "Emausaurus",
           "Eoraptor",
           "Eotyrannus",
           "Erketu",
           "Erlikosaurus",
           "Euhelopus",
           "Euoplocephalus",
           "Europasaurus",
           "Eustreptospondylus",
           "Fukuiraptor",
           "Fukuisauru",
           "Gallimimus",
           "Gargoyleosaurus",
           "Garudimimus",
           "Gasosaurus",
           "Gasparinisaura",
           "Gastonia",
           "Giganotosaurus",
           "Gilmoreosaurus",
           "Giraffatitan",
           "Gobisaurus",
           "Gorgosaurus",
           "Goyocephale",
           "Gryposaurus",
           "Guaibasaurus",
           "Guanlong",
           "Hadrosaurus",
           "Hagryphus",
           "Haplocanthosaurus",
           "Harpymimus",
           "Herrerasaurus",
           "Hesperosaurus",
           "Heterodontosaurus",
           "Heyuannia",
           "Homalocephale",
           "Huayangosaurus",
           "Hylaeosaurus",
           "Hypacrosaurus",
           "Hypsilophodon",
           "Iguanodon",
           "Indosuchus",
           "Irritator",
           "Janenschia",
           "Jaxartosaurus",
           "Jingshanosaurus",
           "Jobaria",
           "Juravenator",
           "Kentrosaurus",
           "Khaan",
           "Kotasaurus",
           "Kritosaurus",
           "Lambeosaurus",
           "Leaellynasaura",
           "Leptoceratops",
           "Ligabuesaurus",
           "Liliensternus",
           "Lophorhothon",
           "Lophostropheus",
           "Lufengosaurus",
           "Lurdusaurus",
           "Lycorhinus",
           "Magyarosaurus",
           "Maiasaura",
           "Majungasaurus",
           "Malawisaurus",
           "Mamenchisaurus",
           "Mapusaurus",
           "Marshosaurus",
           "Masiakasaurus",
           "Massospondylus",
           "Maxakalisaurus",
           "Megalosaurus",
           "Melanorosaurus",
           "Metriacanthosaurus",
           "Microceratus",
           "Micropachycephalosaurus",
           "Microraptor",
           "Minmi",
           "Monolophosaurus",
           "Mononykus",
           "Mussaurus",
           "Muttaburrasaurus",
           "Nanshiungosaurus",
           "Nedoceratops",
           "Nemegtosaurus",
           "Neovenator",
           "Neuquenosaurus",
           "Nigersaurus",
           "Noasaurus",
           "Nodosaurus",
           "Nomingia",
           "Nothronychus",
           "Nqwebasaurus",
           "Omeisaurus",
           "Opisthocoelicaudia",
           "Ornitholestes",
           "Ornithomimus",
           "Orodromeus",
           "Oryctodromeus",
           "Othnielia",
           "Ouranosaurus",
           "Oviraptor",
           "Pachycephalosaurus",
           "Pachyrhinosaurus",
           "Panoplosaurus",
           "Pantydraco",
           "Paralititan",
           "Parasaurolophus",
           "Parksosaurus",
           "Patagosaurus",
           "Pelicanimimus",
           "Pentaceratops",
           "Piatnitzkysauru",
           "Pinacosauru",
           "Plateosauru",
           "Podokesauru",
           "Poekilopleuro",
           "Polacanthu",
           "Prenocephal",
           "Probactrosauru",
           "Proceratosauru",
           "Procompsognathu",
           "Prosaurolophu",
           "Protarchaeoptery",
           "Protoceratop",
           "Protohadro",
           "Psittacosauru",
           "Quaesitosauru",
           "Rebbachisauru",
           "Rhabdodo",
           "Rhoetosauru",
           "Rincheni",
           "Riojasauru",
           "Saichania",
           "Saltasaurus",
           "Sarcosaurus",
           "Saurolophus",
           "Sauropelta",
           "Saurophaganax",
           "Saurornithoides",
           "Scelidosaurus",
           "Scutellosaurus",
           "Secernosaurus",
           "Segisaurus",
           "Segnosaurus",
           "Shanag",
           "Shantungosaurus",
           "Shunosaurus",
           "Shuvuuia",
           "Silvisaurus",
           "Sinocalliopteryx",
           "Sinornithosaurus",
           "Sinosauropteryx",
           "Sinovenator",
           "Sinraptor",
           "Sonidosaurus",
           "Spinosaurus",
           "Staurikosaurus",
           "Stegoceras",
           "Stegosaurus",
           "Stenopelix",
           "Struthiomimus",
           "Struthiosaurus",
           "Styracosaurus",
           "Suchomimus",
           "Supersaurus",
           "Talarurus",
           "Tarbosaurus",
           "Tarchia",
           "Telmatosaurus",
           "Tenontosaurus",
           "Thecodontosaurus",
           "Thescelosaurus",
           "Torosaurus",
           "Torvosaurus",
           "Triceratops",
           "Troodon",
           "Tsintaosaurus",
           "Tuojiangosaurus",
           "Tylocephale",
           "Tyrannosaurus",
           "Unenlagia",
           "Urbacodon",
           "Utahraptor",
           "Valdosaurus",
           "Velociraptor",
           "Vulcanodon",
           "Yandusaurus",
           "Yangchuanosaurus",
           "Yimenosaurus",
           "Yinlong",
           "Yuanmousaurus",
           "Yunnanosaurus",
           "Zalmoxes",
           "Zephyrosaurus"
           ]
        timer = Timer()
        for dinosaur in dinosaur_names:
            timer.setTimeout(self.print_meaning(dinosaur), 3000)

if __name__ == '__main__':
    scraper = NaturalHistoryMuseumScraper()
    scraper.meanings()
