/* Uses data scraped from the Natural History Museum website which was printed out to build this method for all 294 dinosaurs */

export function getType(dinosaur) {

  switch(dinosaur) {

    case 'Aardonyx': return ' sauropod';
    case 'Abelisaurus': return ' large theropod';
    case 'Achelousaurus': return ' ceratopsian';
    case 'Achillobator': return ' large theropod';
    case 'Acrocanthosaurus': return ' large theropod';
    case 'Aegyptosaurus': return ' sauropod';
    case 'Afrovenator': return ' large theropod';
    case 'Agilisaurus': return ' euornithopod';
    case 'Alamosaurus': return ' sauropod';
    case 'Albertaceratops': return ' ceratopsian';
    case 'Albertosaurus': return ' large theropod';
    case 'Alectrosaurus': return ' large theropod';
    case 'Alioramus': return ' large theropod';
    case 'Allosaurus': return ' large theropod';
    case 'Alvarezsaurus': return ' small theropod';
    case 'Amargasaurus': return ' sauropod';
    case 'Ammosaurus': return ' sauropod';
    case 'Ampelosaurus': return ' sauropod';
    case 'Amygdalodon': return ' sauropod';
    case 'Anchiceratops': return ' ceratopsian';
    case 'Anchisaurus': return ' sauropod';
    case 'Ankylosaurus': return ' armoured dinosaur';
    case 'Anserimimus': return ' large theropod';
    case 'Antarctosaurus': return ' sauropod';
    case 'Apatosaurus': return ' sauropod';
    case 'Aragosaurus': return ' sauropod';
    case 'Aralosaurus': return ' euornithopod';
    case 'Archaeoceratops': return ' ceratopsian';
    case 'Archaeopteryx': return ' small theropod';
    case 'Archaeornithomimus': return ' small theropod';
    case 'Argentinosaurus': return ' sauropod';
    case 'Arrhinoceratops': return ' ceratopsian';
    case 'Atlascopcosaurus': return ' euornithopod';
    case 'Aucasaurus': return ' large theropod';
    case 'Austrosaurus': return ' sauropod';
    case 'Avaceratops': return ' ceratopsian';
    case 'Avimimus': return ' small theropod';
    case 'Bactrosaurus': return ' euornithopod';
    case 'Bagaceratops': return ' ceratopsian';
    case 'Bambiraptor': return ' small theropod';
    case 'Barapasaurus': return ' sauropod';
    case 'Barosaurus': return ' sauropod';
    case 'Baryonyx': return ' large theropod';
    case 'Becklespinax': return ' large theropod';
    case 'Beipiaosaurus': return ' small theropod';
    case 'Bellusaurus': return ' sauropod';
    case 'Borogovia': return ' small theropod';
    case 'Brachiosaurus': return ' sauropod';
    case 'Brachylophosaurus': return ' euornithopod';
    case 'Brachytrachelopan': return ' sauropod';
    case 'Buitreraptor': return ' small theropod';
    case 'Camarasaurus': return ' sauropod';
    case 'Camptosaurus': return ' euornithopod';
    case 'Carcharodontosaurus': return ' large theropod';
    case 'Carnotaurus': return ' large theropod';
    case 'Caudipteryx': return ' small theropod';
    case 'Cedarpelta': return ' armoured dinosaur';
    case 'Centrosaurus': return ' ceratopsian';
    case 'Ceratosaurus': return ' large theropod';
    case 'Cetiosauriscus': return ' sauropod';
    case 'Cetiosaurus': return ' sauropod';
    case 'Chaoyangsaurus': return ' ceratopsian';
    case 'Chasmosaurus': return ' ceratopsian';
    case 'Chindesaurus': return ' small theropod';
    case 'Chinshakiangosaurus': return ' sauropod';
    case 'Chirostenotes': return ' small theropod';
    case 'Chubutisaurus': return ' sauropod';
    case 'Chungkingosaurus': return ' armoured dinosaur';
    case 'Citipati': return ' small theropod';
    case 'Coelophysis': return ' small theropod';
    case 'Coelurus': return ' small theropod';
    case 'Coloradisaurus': return ' sauropod';
    case 'Compsognathus': return ' small theropod';
    case 'Conchoraptor': return ' small theropod';
    case 'Confuciusornis': return ' small theropod';
    case 'Corythosaurus': return ' euornithopod';
    case 'Cryolophosaurus': return ' large theropod';
    case 'Dacentrurus': return ' armoured dinosaur';
    case 'Daspletosaurus': return ' large theropod';
    case 'Datousaurus': return ' sauropod';
    case 'Deinocheirus': return ' large theropod';
    case 'Deltadromeus': return ' large theropod';
    case 'Dicraeosaurus': return ' sauropod';
    case 'Dilophosaurus': return ' large theropod';
    case 'Diplodocus': return ' sauropod';
    case 'Dromaeosaurus': return ' small theropod';
    case 'Dromiceiomimus': return ' large theropod';
    case 'Dryosaurus': return ' euornithopod';
    case 'Dryptosaurus': return ' large theropod';
    case 'Edmontonia': return ' armoured dinosaur';
    case 'Edmontosaurus': return ' euornithopod';
    case 'Einiosaurus': return ' ceratopsian';
    case 'Elaphrosaurus': return ' large theropod';
    case 'Emausaurus': return ' armoured dinosaur';
    case 'Eoraptor': return ' small theropod';
    case 'Eotyrannus': return ' large theropod';
    case 'Erketu': return ' sauropod';
    case 'Erlikosaurus': return ' small theropod';
    case 'Euhelopus': return ' sauropod';
    case 'Euoplocephalus': return ' armoured dinosaur';
    case 'Europasaurus': return ' sauropod';
    case 'Eustreptospondylus': return ' large theropod';
    case 'Fukuiraptor': return ' large theropod';
    case 'Gallimimus': return ' large theropod';
    case 'Gargoyleosaurus': return ' armoured dinosaur';
    case 'Garudimimus': return ' large theropod';
    case 'Gasosaurus': return ' small theropod';
    case 'Gasparinisaura': return ' euornithopod';
    case 'Gastonia': return ' armoured dinosaur';
    case 'Giganotosaurus': return ' large theropod';
    case 'Gilmoreosaurus': return ' euornithopod';
    case 'Giraffatitan': return ' sauropod';
    case 'Gobisaurus': return ' armoured dinosaur';
    case 'Gorgosaurus': return ' large theropod';
    case 'Goyocephale': return ' large theropod';
    case 'Gryposaurus': return ' euornithopod';
    case 'Guaibasaurus': return ' small theropod';
    case 'Guanlong': return ' small theropod';
    case 'Hadrosaurus': return ' euornithopod';
    case 'Hagryphus': return ' small theropod';
    case 'Haplocanthosaurus': return ' sauropod';
    case 'Harpymimus': return ' small theropod';
    case 'Herrerasaurus': return ' small theropod';
    case 'Hesperosaurus': return ' armoured dinosaur';
    case 'Heterodontosaurus': return ' euornithopod';
    case 'Heyuannia': return ' small theropod';
    case 'Homalocephale': return ' euornithopod';
    case 'Huayangosaurus': return ' armoured dinosaur';
    case 'Hylaeosaurus': return ' armoured dinosaur';
    case 'Hypacrosaurus': return ' euornithopod';
    case 'Hypsilophodon': return ' euornithopod';
    case 'Iguanodon': return ' euornithopod';
    case 'Indosuchus': return ' large theropod';
    case 'Irritator': return ' large theropod';
    case 'Janenschia': return ' sauropod';
    case 'Jaxartosaurus': return ' euornithopod';
    case 'Jingshanosaurus': return ' sauropod';
    case 'Jobaria': return ' sauropod';
    case 'Juravenator': return ' small theropod';
    case 'Kentrosaurus': return ' armoured dinosaur';
    case 'Khaan': return ' small theropod';
    case 'Kotasaurus': return ' sauropod';
    case 'Kritosaurus': return ' euornithopod';
    case 'Lambeosaurus': return ' euornithopod';
    case 'Leaellynasaura': return ' euornithopod';
    case 'Leptoceratops': return ' ceratopsian';
    case 'Ligabuesaurus': return ' sauropod';
    case 'Liliensternus': return ' small theropod';
    case 'Lophorhothon': return ' euornithopod';
    case 'Lophostropheus': return ' large theropod';
    case 'Lufengosaurus': return ' sauropod';
    case 'Lurdusaurus': return ' euornithopod';
    case 'Lycorhinus': return ' euornithopod';
    case 'Magyarosaurus': return ' sauropod';
    case 'Maiasaura': return ' euornithopod';
    case 'Majungasaurus': return ' large theropod';
    case 'Malawisaurus': return ' sauropod';
    case 'Mamenchisaurus': return ' sauropod';
    case 'Mapusaurus': return ' large theropod';
    case 'Marshosaurus': return ' large theropod';
    case 'Masiakasaurus': return ' small theropod';
    case 'Massospondylus': return ' sauropod';
    case 'Maxakalisaurus': return ' sauropod';
    case 'Megalosaurus': return ' large theropod';
    case 'Melanorosaurus': return ' sauropod';
    case 'Metriacanthosaurus': return ' large theropod';
    case 'Microceratus': return ' ceratopsian';
    case 'Micropachycephalosaurus': return ' ceratopsian';
    case 'Microraptor': return ' small theropod';
    case 'Minmi': return ' armoured dinosaur';
    case 'Monolophosaurus': return ' large theropod';
    case 'Mononykus': return ' small theropod';
    case 'Mussaurus': return ' sauropod';
    case 'Muttaburrasaurus': return ' euornithopod';
    case 'Nanshiungosaurus': return ' large theropod';
    case 'Nedoceratops': return ' ceratopsian';
    case 'Nemegtosaurus': return ' sauropod';
    case 'Neovenator': return ' large theropod';
    case 'Neuquenosaurus': return ' sauropod';
    case 'Nigersaurus': return ' sauropod';
    case 'Noasaurus': return ' small theropod';
    case 'Nodosaurus': return ' armoured dinosaur';
    case 'Nomingia': return ' small theropod';
    case 'Nothronychus': return ' large theropod';
    case 'Nqwebasaurus': return ' small theropod';
    case 'Omeisaurus': return ' sauropod';
    case 'Opisthocoelicaudia': return ' sauropod';
    case 'Ornitholestes': return ' small theropod';
    case 'Ornithomimus': return ' large theropod';
    case 'Orodromeus': return ' euornithopod';
    case 'Oryctodromeus': return ' euornithopod';
    case 'Othnielia': return ' euornithopod';
    case 'Ouranosaurus': return ' euornithopod';
    case 'Oviraptor': return ' small theropod';
    case 'Pachycephalosaurus': return ' euornithopod';
    case 'Pachyrhinosaurus': return ' ceratopsian';
    case 'Panoplosaurus': return ' armoured dinosaur';
    case 'Pantydraco': return ' euornithopod';
    case 'Paralititan': return ' sauropod';
    case 'Parasaurolophus': return ' euornithopod';
    case 'Parksosaurus': return ' euornithopod';
    case 'Patagosaurus': return ' sauropod';
    case 'Pelicanimimus': return ' small theropod';
    case 'Pentaceratops': return ' ceratopsian';
    case 'Saichania': return ' armoured dinosaur';
    case 'Saltasaurus': return ' sauropod';
    case 'Sarcosaurus': return ' small theropod';
    case 'Saurolophus': return ' euornithopod';
    case 'Sauropelta': return ' armoured dinosaur';
    case 'Saurophaganax': return ' large theropod';
    case 'Saurornithoides': return ' small theropod';
    case 'Scelidosaurus': return ' armoured dinosaur';
    case 'Scutellosaurus': return ' armoured dinosaur';
    case 'Secernosaurus': return ' euornithopod';
    case 'Segisaurus': return ' small theropod';
    case 'Segnosaurus': return ' large theropod';
    case 'Shanag': return ' small theropod';
    case 'Shantungosaurus': return ' euornithopod';
    case 'Shunosaurus': return ' sauropod';
    case 'Shuvuuia': return ' small theropod';
    case 'Silvisaurus': return ' armoured dinosaur';
    case 'Sinocalliopteryx': return ' small theropod';
    case 'Sinornithosaurus': return ' small theropod';
    case 'Sinosauropteryx': return ' small theropod';
    case 'Sinovenator': return ' small theropod';
    case 'Sinraptor': return ' large theropod';
    case 'Sonidosaurus': return ' sauropod';
    case 'Spinosaurus': return ' large theropod';
    case 'Staurikosaurus': return ' large theropod';
    case 'Stegoceras': return ' euornithopod';
    case 'Stegosaurus': return ' armoured dinosaur';
    case 'Stenopelix': return ' ceratopsian';
    case 'Struthiomimus': return ' small theropod';
    case 'Struthiosaurus': return ' armoured dinosaur';
    case 'Styracosaurus': return ' ceratopsian';
    case 'Suchomimus': return ' large theropod';
    case 'Supersaurus': return ' sauropod';
    case 'Talarurus': return ' armoured dinosaur';
    case 'Tarbosaurus': return ' large theropod';
    case 'Tarchia': return ' armoured dinosaur';
    case 'Telmatosaurus': return ' euornithopod';
    case 'Tenontosaurus': return ' euornithopod';
    case 'Thecodontosaurus': return ' sauropod';
    case 'Thescelosaurus': return ' euornithopod';
    case 'Torosaurus': return ' ceratopsian';
    case 'Torvosaurus': return ' large theropod';
    case 'Triceratops': return ' ceratopsian';
    case 'Troodon': return ' small theropod';
    case 'Tsintaosaurus': return ' euornithopod';
    case 'Tuojiangosaurus': return ' armoured dinosaur';
    case 'Tylocephale': return ' euornithopod';
    case 'Tyrannosaurus': return ' large theropod';
    case 'Unenlagia': return ' small theropod';
    case 'Urbacodon': return ' small theropod';
    case 'Utahraptor': return ' large theropod';
    case 'Valdosaurus': return ' euornithopod';
    case 'Velociraptor': return ' small theropod';
    case 'Vulcanodon': return ' sauropod';
    case 'Yandusaurus': return ' euornithopod';
    case 'Yangchuanosaurus': return ' large theropod';
    case 'Yimenosaurus': return ' sauropod';
    case 'Yinlong': return ' ceratopsian';
    case 'Yuanmousaurus': return ' sauropod';
    case 'Yunnanosaurus': return ' sauropod';
    case 'Zalmoxes': return ' euornithopod';
    case 'Zephyrosaurus': return ' euornithopod';

}
}
